---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
  application:
      name: discovery   # ==> This is Service-Id

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    appname: discovery-cluster
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: discovery-replica-1
  application:
    name: discovery   # ==> This is Service-Id

server:
  port: 9001

eureka:
  instance:
    hostname: localhost
    appname: discovery-cluster
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/
#,http://my-eureka-server-vn.com:9003/eureka/

---
spring:
  profiles: discovery-replica-2
  application:
    name: discovery   # ==> This is Service-Id

server:
  port: 9002

eureka:
  instance:
    hostname: localhost
    appname: discovery-cluster
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/