spring:
  profiles: default
  application:
    name: discovery # ==> This is Service-Id

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
#    appname: eureka-cluster
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#eureka.client.register-with-eureka=true PRODUCTION


---

spring:
  profiles: discovery-replica-1
  application:
    name: discovery # ==> This is Service-Id

server:
  port: 9001

eureka:
  instance:
    hostname: localhost
#    appname: eureka-cluster
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/,http://localhost:9003/eureka/


---

spring:
  profiles: discovery-replica-2
  application:
    name: discovery # ==> This is Service-Id

server:
  port: 9002

eureka:
  instance:
    hostname: localhost
#    appname: eureka-cluster
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9003/eureka/


---

spring:
  profiles: discovery-replica-3
  application:
    name: discovery # ==> This is Service-Id

server:
  port: 9003

eureka:
  instance:
    hostname: localhost
#    appname: eureka-cluster
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/