spring:
  application:
    name: gateway

server:
  port: 8080
 
eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8082/eureka/

# zuul routes

# Book service
# Rating service
# Simple service
# Discovery

zuul:
  routes:
    discovery:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8082
    book-service:
      path: /book-service/**
      sensitive-headers: Set-Cookie,Authorization
    rating-service:
      path: /rating-service/**
      sensitive-headers: Set-Cookie,Authorization
    simple-service:
      path: /simple-service/**
      sensitive-headers: Set-Cookie,Authorization

hystrix.command.discovery.execution.isolation.thread.timeoutInMilliseconds: 60000
hystrix.command.book-service.execution.isolation.thread.timeoutInMilliseconds: 60000
hystrix.command.rating-service.execution.isolation.thread.timeoutInMilliseconds: 60000
hystrix.command.simple-service.execution.isolation.thread.timeoutInMilliseconds: 60000
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000