spring:
  application:
    name: rating-service

server:
  port: 8084

# eureka client
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8082/eureka/}