spring:
  application:
    name: rating-service

server:
  port: 8084

# eureka client
eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8082/eureka/