spring:
  application:
    name: simple-service

server:
  port: 8085

# eureka client
eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8082/eureka/

user:
  environment: Production

---
spring:
  profiles: dev

user:
  environment: Development