INSERT INTO ROLE (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO ROLE (ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, USERNAME, EMAIL, ACTIVE, PASSWORD)
  VALUES (1, 'Administrator', '', 'ADMIN', 'admin@xxx.com', 'Y', '$2a$10$Pr6x/DYehqYCcYwG76RB1eFYNTIWgLbBkVdY98Gumd.KFpSEzrd1e');

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 2);